version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

    working_dir: /
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - db
    command: postgres -c log_statement=all -c
      shared_preload_libraries=pg_stat_statements -c
      pg_stat_statements.max=10000 -c pg_stat_statements.track=all -c
      shared_preload_libraries=auto_explain -c auto_explain.log_min_duration=0
      -c auto_explain.log_nested_statements=true

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - db
    command: redis-server

networks:
  db:
